# Generated by Django 2.0.2 on 2018-02-23 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180223_1245'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ramo', models.CharField(max_length=30, verbose_name='Ramo de atuação')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='advogadoprofile',
            name='cpf',
            field=models.CharField(max_length=20, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='advogadoprofile',
            name='telefone',
            field=models.CharField(max_length=20, verbose_name='Telefone'),
        ),
    ]
