# Generated by Django 2.0.2 on 2018-02-23 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180223_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposta',
            name='aceita',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ordemdeservico',
            name='status',
            field=models.CharField(choices=[('CRIADA', 'Criada'), ('DELEGADA', 'Delegada'), ('FINALIZADA', 'Finalizada')], default='Criada', max_length=30),
        ),
    ]
