# Generated by Django 2.0.2 on 2018-02-23 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180223_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemdeservico',
            name='descricao',
            field=models.TextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='ordemdeservico',
            name='titulo',
            field=models.CharField(max_length=25, verbose_name='Título'),
        ),
    ]
