# Generated by Django 2.0.2 on 2018-02-24 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20180223_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemdeservico',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
