# Generated by Django 2.0.2 on 2018-02-26 20:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20180224_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposta',
            name='advogado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
